version: "3.7"
services:
  api:
    container_name: api
    build:
      context: .
      args:
        - SERVICE=api
    ports:
      - 8420:8420
    links:
      - redis

  observer:
    container_name: observer
    build:
      context: .
      args:
        - SERVICE=observer
    links:
      - redis

  syncmarkets:
    container_name: syncmarkets
    build:
      context: .
      args:
        - SERVICE=syncmarkets
    links:
      - redis

  redis:
    container_name: redis
    image: neojt/mredis
    ports:
      - 6379:6379
